#configure Mysql connection

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todos
    username: admin
    password: nopass
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
banner:
  location: classpath:/META-INF/banner-dev.txt