-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 10:08:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `todos` ;

-- -----------------------------------------------------
-- Schema todos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todos` DEFAULT CHARACTER SET utf8 ;
USE `todos` ;

-- -----------------------------------------------------
-- Table `todos`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todos`.`users` ;

CREATE TABLE IF NOT EXISTS `todos`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NULL,
  `password` VARBINARY(255) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `users_user_name_ux` (`user_name` ASC),
  UNIQUE INDEX `users_email_ux` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todos`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todos`.`tasks` ;

CREATE TABLE IF NOT EXISTS `todos`.`tasks` (
  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `task` VARCHAR(255) NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`task_id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `tasks_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `todos`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

